//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBazaar.Dalc.Dtos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryField()
        {
            this.PostingFields = new HashSet<PostingField>();
        }
    
        public long Id { get; set; }
        public long CategoryId { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostingField> PostingFields { get; set; }
    }
}
