//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBazaar.Dalc.Dtos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageReference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImageReference()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public long Id { get; set; }
        public string Provider { get; set; }
        public string Url { get; set; }
        public string InternalAddress1 { get; set; }
        public string InternalAddress2 { get; set; }
        public string InternalAddress3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}
