//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBazaar.Dalc.Dtos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostingField
    {
        public long Id { get; set; }
        public long PostingId { get; set; }
        public long FieldId { get; set; }
        public Nullable<bool> BooleanValue { get; set; }
        public string TextValue { get; set; }
        public Nullable<int> IntegerValue { get; set; }
        public Nullable<decimal> DecimarlValue { get; set; }
    
        public virtual CategoryField CategoryField { get; set; }
        public virtual Posting Posting { get; set; }
    }
}
