//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBazaar.Dalc.Dtos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Translation()
        {
            this.TranslationValues = new HashSet<TranslationValue>();
        }
    
        public long Id { get; set; }
        public long TypeId { get; set; }
        public string Code { get; set; }
        public int EnumId { get; set; }
    
        public virtual TranslationType TranslationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranslationValue> TranslationValues { get; set; }
    }
}
